[package]
name = "ricci_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "ricci_core"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.20"
features = ["extension-module"]

[dependencies.numpy]
version = "0.20"
features = ["nalgebra"]
